site_name: ${{values.name | dump}}
site_description: ${{values.description | dump}}

nav:
  - Introduction: terraform/README.md
  - API Reference:
    - Overview: terraform/README.md
    - Endpoints: terraform/README.md

plugins:
  - techdocs-core
